name: QuranLock
options:
  bundleIdPrefix: com.rezaimia
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"

targets:
  QuranLock:
    type: application
    platform: iOS
    sources:
      - path: QuranLock
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rezaimia.QuranLock
        PRODUCT_NAME: Iqra
        MARKETING_VERSION: "2.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: QuranLock/Info.plist
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: J875R59LND
        PROVISIONING_PROFILE_SPECIFIER: "QuranLock AppStore"
        CODE_SIGN_IDENTITY: "Apple Distribution"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
