name: QuranLock
options:
  bundleIdPrefix: com.rezaimia
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "16.2"
  generateEmptyDirectories: true
  defaultConfig: Release
settings:
  base:
    SWIFT_VERSION: "5.9"
    CODE_SIGNING_ALLOWED: "NO"
    CODE_SIGNING_REQUIRED: "NO"
    CODE_SIGN_IDENTITY: ""
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "11.0.0"
targets:
  QuranLock:
    type: application
    platform: iOS
    sources:
      - path: QuranLock
        excludes:
          - "**/.DS_Store"
          - "Resources/adhan.mp3"
    resources:
      - path: QuranLock/Resources/adhan.mp3
        buildPhase: resources
      - path: QuranLock/Resources/quran_data.json
        buildPhase: resources
      - path: QuranLock/Resources/Assets.xcassets
        buildPhase: resources
      - path: QuranLock/GoogleService-Info.plist
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rezaimia.QuranLock
        PRODUCT_NAME: Iqra
        MARKETING_VERSION: "3.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: QuranLock/Info.plist
        CODE_SIGN_STYLE: Manual
        CODE_SIGNING_ALLOWED: "YES"
        CODE_SIGNING_REQUIRED: "YES"
        CODE_SIGN_ENTITLEMENTS: QuranLock/QuranLock.entitlements
        DEVELOPMENT_TEAM: J875R59LND
        PROVISIONING_PROFILE_SPECIFIER: "QuranLock AppStore New"
        CODE_SIGN_IDENTITY: "Apple Distribution"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        ENABLE_USER_SCRIPT_SANDBOXING: "NO"
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "Apple Development"
          PROVISIONING_PROFILE_SPECIFIER: ""
          CODE_SIGN_STYLE: Automatic
    dependencies:
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseAuth
schemes:
  QuranLock:
    shared: true
    build:
      targets:
        QuranLock: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Release
    archive:
      config: Release
