// ==========================================
// QURANLOCK V5 - DONNÉES COMPLÈTES
// ==========================================

// 114 SOURATES
const SURAHS = [
    { id: 1, name: "Al-Fatiha", nameAr: "الفاتحة", verses: 7, meaning: "L'Ouverture", revelation: "Mecque" },
    { id: 2, name: "Al-Baqarah", nameAr: "البقرة", verses: 286, meaning: "La Vache", revelation: "Médine" },
    { id: 3, name: "Al-Imran", nameAr: "آل عمران", verses: 200, meaning: "La Famille d'Imran", revelation: "Médine" },
    { id: 4, name: "An-Nisa", nameAr: "النساء", verses: 176, meaning: "Les Femmes", revelation: "Médine" },
    { id: 5, name: "Al-Ma'idah", nameAr: "المائدة", verses: 120, meaning: "La Table Servie", revelation: "Médine" },
    { id: 6, name: "Al-An'am", nameAr: "الأنعام", verses: 165, meaning: "Les Bestiaux", revelation: "Mecque" },
    { id: 7, name: "Al-A'raf", nameAr: "الأعراف", verses: 206, meaning: "Les Hauteurs", revelation: "Mecque" },
    { id: 8, name: "Al-Anfal", nameAr: "الأنفال", verses: 75, meaning: "Le Butin", revelation: "Médine" },
    { id: 9, name: "At-Tawbah", nameAr: "التوبة", verses: 129, meaning: "Le Repentir", revelation: "Médine" },
    { id: 10, name: "Yunus", nameAr: "يونس", verses: 109, meaning: "Jonas", revelation: "Mecque" },
    { id: 11, name: "Hud", nameAr: "هود", verses: 123, meaning: "Hud", revelation: "Mecque" },
    { id: 12, name: "Yusuf", nameAr: "يوسف", verses: 111, meaning: "Joseph", revelation: "Mecque" },
    { id: 13, name: "Ar-Ra'd", nameAr: "الرعد", verses: 43, meaning: "Le Tonnerre", revelation: "Médine" },
    { id: 14, name: "Ibrahim", nameAr: "إبراهيم", verses: 52, meaning: "Abraham", revelation: "Mecque" },
    { id: 15, name: "Al-Hijr", nameAr: "الحجر", verses: 99, meaning: "Al-Hijr", revelation: "Mecque" },
    { id: 16, name: "An-Nahl", nameAr: "النحل", verses: 128, meaning: "Les Abeilles", revelation: "Mecque" },
    { id: 17, name: "Al-Isra", nameAr: "الإسراء", verses: 111, meaning: "Le Voyage Nocturne", revelation: "Mecque" },
    { id: 18, name: "Al-Kahf", nameAr: "الكهف", verses: 110, meaning: "La Caverne", revelation: "Mecque" },
    { id: 19, name: "Maryam", nameAr: "مريم", verses: 98, meaning: "Marie", revelation: "Mecque" },
    { id: 20, name: "Ta-Ha", nameAr: "طه", verses: 135, meaning: "Ta-Ha", revelation: "Mecque" },
    { id: 21, name: "Al-Anbiya", nameAr: "الأنبياء", verses: 112, meaning: "Les Prophètes", revelation: "Mecque" },
    { id: 22, name: "Al-Hajj", nameAr: "الحج", verses: 78, meaning: "Le Pèlerinage", revelation: "Médine" },
    { id: 23, name: "Al-Mu'minun", nameAr: "المؤمنون", verses: 118, meaning: "Les Croyants", revelation: "Mecque" },
    { id: 24, name: "An-Nur", nameAr: "النور", verses: 64, meaning: "La Lumière", revelation: "Médine" },
    { id: 25, name: "Al-Furqan", nameAr: "الفرقان", verses: 77, meaning: "Le Discernement", revelation: "Mecque" },
    { id: 26, name: "Ash-Shu'ara", nameAr: "الشعراء", verses: 227, meaning: "Les Poètes", revelation: "Mecque" },
    { id: 27, name: "An-Naml", nameAr: "النمل", verses: 93, meaning: "Les Fourmis", revelation: "Mecque" },
    { id: 28, name: "Al-Qasas", nameAr: "القصص", verses: 88, meaning: "Le Récit", revelation: "Mecque" },
    { id: 29, name: "Al-Ankabut", nameAr: "العنكبوت", verses: 69, meaning: "L'Araignée", revelation: "Mecque" },
    { id: 30, name: "Ar-Rum", nameAr: "الروم", verses: 60, meaning: "Les Romains", revelation: "Mecque" },
    { id: 31, name: "Luqman", nameAr: "لقمان", verses: 34, meaning: "Luqman", revelation: "Mecque" },
    { id: 32, name: "As-Sajdah", nameAr: "السجدة", verses: 30, meaning: "La Prosternation", revelation: "Mecque" },
    { id: 33, name: "Al-Ahzab", nameAr: "الأحزاب", verses: 73, meaning: "Les Coalisés", revelation: "Médine" },
    { id: 34, name: "Saba", nameAr: "سبأ", verses: 54, meaning: "Saba", revelation: "Mecque" },
    { id: 35, name: "Fatir", nameAr: "فاطر", verses: 45, meaning: "Le Créateur", revelation: "Mecque" },
    { id: 36, name: "Ya-Sin", nameAr: "يس", verses: 83, meaning: "Ya-Sin", revelation: "Mecque" },
    { id: 37, name: "As-Saffat", nameAr: "الصافات", verses: 182, meaning: "Les Rangés", revelation: "Mecque" },
    { id: 38, name: "Sad", nameAr: "ص", verses: 88, meaning: "Sad", revelation: "Mecque" },
    { id: 39, name: "Az-Zumar", nameAr: "الزمر", verses: 75, meaning: "Les Groupes", revelation: "Mecque" },
    { id: 40, name: "Ghafir", nameAr: "غافر", verses: 85, meaning: "Le Pardonneur", revelation: "Mecque" },
    { id: 41, name: "Fussilat", nameAr: "فصلت", verses: 54, meaning: "Les Versets Détaillés", revelation: "Mecque" },
    { id: 42, name: "Ash-Shura", nameAr: "الشورى", verses: 53, meaning: "La Consultation", revelation: "Mecque" },
    { id: 43, name: "Az-Zukhruf", nameAr: "الزخرف", verses: 89, meaning: "L'Ornement", revelation: "Mecque" },
    { id: 44, name: "Ad-Dukhan", nameAr: "الدخان", verses: 59, meaning: "La Fumée", revelation: "Mecque" },
    { id: 45, name: "Al-Jathiyah", nameAr: "الجاثية", verses: 37, meaning: "L'Agenouillée", revelation: "Mecque" },
    { id: 46, name: "Al-Ahqaf", nameAr: "الأحقاف", verses: 35, meaning: "Les Dunes", revelation: "Mecque" },
    { id: 47, name: "Muhammad", nameAr: "محمد", verses: 38, meaning: "Muhammad", revelation: "Médine" },
    { id: 48, name: "Al-Fath", nameAr: "الفتح", verses: 29, meaning: "La Victoire", revelation: "Médine" },
    { id: 49, name: "Al-Hujurat", nameAr: "الحجرات", verses: 18, meaning: "Les Appartements", revelation: "Médine" },
    { id: 50, name: "Qaf", nameAr: "ق", verses: 45, meaning: "Qaf", revelation: "Mecque" },
    { id: 51, name: "Adh-Dhariyat", nameAr: "الذاريات", verses: 60, meaning: "Les Vents", revelation: "Mecque" },
    { id: 52, name: "At-Tur", nameAr: "الطور", verses: 49, meaning: "Le Mont", revelation: "Mecque" },
    { id: 53, name: "An-Najm", nameAr: "النجم", verses: 62, meaning: "L'Étoile", revelation: "Mecque" },
    { id: 54, name: "Al-Qamar", nameAr: "القمر", verses: 55, meaning: "La Lune", revelation: "Mecque" },
    { id: 55, name: "Ar-Rahman", nameAr: "الرحمن", verses: 78, meaning: "Le Miséricordieux", revelation: "Médine" },
    { id: 56, name: "Al-Waqi'ah", nameAr: "الواقعة", verses: 96, meaning: "L'Événement", revelation: "Mecque" },
    { id: 57, name: "Al-Hadid", nameAr: "الحديد", verses: 29, meaning: "Le Fer", revelation: "Médine" },
    { id: 58, name: "Al-Mujadila", nameAr: "المجادلة", verses: 22, meaning: "La Discussion", revelation: "Médine" },
    { id: 59, name: "Al-Hashr", nameAr: "الحشر", verses: 24, meaning: "L'Exode", revelation: "Médine" },
    { id: 60, name: "Al-Mumtahanah", nameAr: "الممتحنة", verses: 13, meaning: "L'Éprouvée", revelation: "Médine" },
    { id: 61, name: "As-Saff", nameAr: "الصف", verses: 14, meaning: "Le Rang", revelation: "Médine" },
    { id: 62, name: "Al-Jumu'ah", nameAr: "الجمعة", verses: 11, meaning: "Le Vendredi", revelation: "Médine" },
    { id: 63, name: "Al-Munafiqun", nameAr: "المنافقون", verses: 11, meaning: "Les Hypocrites", revelation: "Médine" },
    { id: 64, name: "At-Taghabun", nameAr: "التغابن", verses: 18, meaning: "La Duperie", revelation: "Médine" },
    { id: 65, name: "At-Talaq", nameAr: "الطلاق", verses: 12, meaning: "Le Divorce", revelation: "Médine" },
    { id: 66, name: "At-Tahrim", nameAr: "التحريم", verses: 12, meaning: "L'Interdiction", revelation: "Médine" },
    { id: 67, name: "Al-Mulk", nameAr: "الملك", verses: 30, meaning: "La Royauté", revelation: "Mecque" },
    { id: 68, name: "Al-Qalam", nameAr: "القلم", verses: 52, meaning: "La Plume", revelation: "Mecque" },
    { id: 69, name: "Al-Haqqah", nameAr: "الحاقة", verses: 52, meaning: "L'Inévitable", revelation: "Mecque" },
    { id: 70, name: "Al-Ma'arij", nameAr: "المعارج", verses: 44, meaning: "Les Voies d'Ascension", revelation: "Mecque" },
    { id: 71, name: "Nuh", nameAr: "نوح", verses: 28, meaning: "Noé", revelation: "Mecque" },
    { id: 72, name: "Al-Jinn", nameAr: "الجن", verses: 28, meaning: "Les Djinns", revelation: "Mecque" },
    { id: 73, name: "Al-Muzzammil", nameAr: "المزمل", verses: 20, meaning: "L'Enveloppé", revelation: "Mecque" },
    { id: 74, name: "Al-Muddaththir", nameAr: "المدثر", verses: 56, meaning: "Le Revêtu", revelation: "Mecque" },
    { id: 75, name: "Al-Qiyamah", nameAr: "القيامة", verses: 40, meaning: "La Résurrection", revelation: "Mecque" },
    { id: 76, name: "Al-Insan", nameAr: "الإنسان", verses: 31, meaning: "L'Homme", revelation: "Médine" },
    { id: 77, name: "Al-Mursalat", nameAr: "المرسلات", verses: 50, meaning: "Les Envoyés", revelation: "Mecque" },
    { id: 78, name: "An-Naba", nameAr: "النبأ", verses: 40, meaning: "La Nouvelle", revelation: "Mecque" },
    { id: 79, name: "An-Nazi'at", nameAr: "النازعات", verses: 46, meaning: "Les Anges", revelation: "Mecque" },
    { id: 80, name: "Abasa", nameAr: "عبس", verses: 42, meaning: "Il s'est Renfrogné", revelation: "Mecque" },
    { id: 81, name: "At-Takwir", nameAr: "التكوير", verses: 29, meaning: "L'Obscurcissement", revelation: "Mecque" },
    { id: 82, name: "Al-Infitar", nameAr: "الانفطار", verses: 19, meaning: "La Rupture", revelation: "Mecque" },
    { id: 83, name: "Al-Mutaffifin", nameAr: "المطففين", verses: 36, meaning: "Les Fraudeurs", revelation: "Mecque" },
    { id: 84, name: "Al-Inshiqaq", nameAr: "الانشقاق", verses: 25, meaning: "La Déchirure", revelation: "Mecque" },
    { id: 85, name: "Al-Buruj", nameAr: "البروج", verses: 22, meaning: "Les Constellations", revelation: "Mecque" },
    { id: 86, name: "At-Tariq", nameAr: "الطارق", verses: 17, meaning: "L'Astre Nocturne", revelation: "Mecque" },
    { id: 87, name: "Al-A'la", nameAr: "الأعلى", verses: 19, meaning: "Le Très-Haut", revelation: "Mecque" },
    { id: 88, name: "Al-Ghashiyah", nameAr: "الغاشية", verses: 26, meaning: "L'Enveloppante", revelation: "Mecque" },
    { id: 89, name: "Al-Fajr", nameAr: "الفجر", verses: 30, meaning: "L'Aube", revelation: "Mecque" },
    { id: 90, name: "Al-Balad", nameAr: "البلد", verses: 20, meaning: "La Cité", revelation: "Mecque" },
    { id: 91, name: "Ash-Shams", nameAr: "الشمس", verses: 15, meaning: "Le Soleil", revelation: "Mecque" },
    { id: 92, name: "Al-Layl", nameAr: "الليل", verses: 21, meaning: "La Nuit", revelation: "Mecque" },
    { id: 93, name: "Ad-Duha", nameAr: "الضحى", verses: 11, meaning: "Le Jour Montant", revelation: "Mecque" },
    { id: 94, name: "Ash-Sharh", nameAr: "الشرح", verses: 8, meaning: "L'Ouverture", revelation: "Mecque" },
    { id: 95, name: "At-Tin", nameAr: "التين", verses: 8, meaning: "Le Figuier", revelation: "Mecque" },
    { id: 96, name: "Al-Alaq", nameAr: "العلق", verses: 19, meaning: "L'Adhérence", revelation: "Mecque" },
    { id: 97, name: "Al-Qadr", nameAr: "القدر", verses: 5, meaning: "La Destinée", revelation: "Mecque" },
    { id: 98, name: "Al-Bayyinah", nameAr: "البينة", verses: 8, meaning: "La Preuve", revelation: "Médine" },
    { id: 99, name: "Az-Zalzalah", nameAr: "الزلزلة", verses: 8, meaning: "Le Séisme", revelation: "Médine" },
    { id: 100, name: "Al-Adiyat", nameAr: "العاديات", verses: 11, meaning: "Les Coursiers", revelation: "Mecque" },
    { id: 101, name: "Al-Qari'ah", nameAr: "القارعة", verses: 11, meaning: "Le Fracas", revelation: "Mecque" },
    { id: 102, name: "At-Takathur", nameAr: "التكاثر", verses: 8, meaning: "La Course", revelation: "Mecque" },
    { id: 103, name: "Al-Asr", nameAr: "العصر", verses: 3, meaning: "Le Temps", revelation: "Mecque" },
    { id: 104, name: "Al-Humazah", nameAr: "الهمزة", verses: 9, meaning: "Le Calomniateur", revelation: "Mecque" },
    { id: 105, name: "Al-Fil", nameAr: "الفيل", verses: 5, meaning: "L'Éléphant", revelation: "Mecque" },
    { id: 106, name: "Quraysh", nameAr: "قريش", verses: 4, meaning: "Quraysh", revelation: "Mecque" },
    { id: 107, name: "Al-Ma'un", nameAr: "الماعون", verses: 7, meaning: "L'Aide", revelation: "Mecque" },
    { id: 108, name: "Al-Kawthar", nameAr: "الكوثر", verses: 3, meaning: "L'Abondance", revelation: "Mecque" },
    { id: 109, name: "Al-Kafirun", nameAr: "الكافرون", verses: 6, meaning: "Les Infidèles", revelation: "Mecque" },
    { id: 110, name: "An-Nasr", nameAr: "النصر", verses: 3, meaning: "Le Secours", revelation: "Médine" },
    { id: 111, name: "Al-Masad", nameAr: "المسد", verses: 5, meaning: "Les Fibres", revelation: "Mecque" },
    { id: 112, name: "Al-Ikhlas", nameAr: "الإخلاص", verses: 4, meaning: "Le Monothéisme Pur", revelation: "Mecque" },
    { id: 113, name: "Al-Falaq", nameAr: "الفلق", verses: 5, meaning: "L'Aube Naissante", revelation: "Mecque" },
    { id: 114, name: "An-Nas", nameAr: "الناس", verses: 6, meaning: "Les Hommes", revelation: "Mecque" }
];

// 99 NOMS D'ALLAH
const ALLAH_NAMES = [
    { id: 1, arabic: "الرَّحْمَنُ", transliteration: "Ar-Rahman", meaning: "Le Tout Miséricordieux" },
    { id: 2, arabic: "الرَّحِيمُ", transliteration: "Ar-Rahim", meaning: "Le Très Miséricordieux" },
    { id: 3, arabic: "الْمَلِكُ", transliteration: "Al-Malik", meaning: "Le Souverain" },
    { id: 4, arabic: "الْقُدُّوسُ", transliteration: "Al-Quddus", meaning: "Le Très Saint" },
    { id: 5, arabic: "السَّلاَمُ", transliteration: "As-Salam", meaning: "La Paix" },
    { id: 6, arabic: "الْمُؤْمِنُ", transliteration: "Al-Mu'min", meaning: "Le Garant de la Foi" },
    { id: 7, arabic: "الْمُهَيْمِنُ", transliteration: "Al-Muhaymin", meaning: "Le Surveillant" },
    { id: 8, arabic: "الْعَزِيزُ", transliteration: "Al-Aziz", meaning: "Le Tout Puissant" },
    { id: 9, arabic: "الْجَبَّارُ", transliteration: "Al-Jabbar", meaning: "Le Contraignant" },
    { id: 10, arabic: "الْمُتَكَبِّرُ", transliteration: "Al-Mutakabbir", meaning: "Le Superbe" },
    { id: 11, arabic: "الْخَالِقُ", transliteration: "Al-Khaliq", meaning: "Le Créateur" },
    { id: 12, arabic: "الْبَارِئُ", transliteration: "Al-Bari", meaning: "Le Producteur" },
    { id: 13, arabic: "الْمُصَوِّرُ", transliteration: "Al-Musawwir", meaning: "Le Formateur" },
    { id: 14, arabic: "الْغَفَّارُ", transliteration: "Al-Ghaffar", meaning: "L'Infini Pardonneur" },
    { id: 15, arabic: "الْقَهَّارُ", transliteration: "Al-Qahhar", meaning: "Le Dominateur Suprême" },
    { id: 16, arabic: "الْوَهَّابُ", transliteration: "Al-Wahhab", meaning: "Le Donateur" },
    { id: 17, arabic: "الرَّزَّاقُ", transliteration: "Ar-Razzaq", meaning: "Le Pourvoyeur" },
    { id: 18, arabic: "الْفَتَّاحُ", transliteration: "Al-Fattah", meaning: "L'Ouvreur" },
    { id: 19, arabic: "اَلْعَلِيْمُ", transliteration: "Al-Alim", meaning: "L'Omniscient" },
    { id: 20, arabic: "الْقَابِضُ", transliteration: "Al-Qabid", meaning: "Celui qui retient" },
    { id: 21, arabic: "الْبَاسِطُ", transliteration: "Al-Basit", meaning: "Celui qui étend" },
    { id: 22, arabic: "الْخَافِضُ", transliteration: "Al-Khafid", meaning: "Celui qui abaisse" },
    { id: 23, arabic: "الرَّافِعُ", transliteration: "Ar-Rafi", meaning: "Celui qui élève" },
    { id: 24, arabic: "الْمُعِزُّ", transliteration: "Al-Mu'izz", meaning: "Celui qui honore" },
    { id: 25, arabic: "المُذِلُّ", transliteration: "Al-Mudhill", meaning: "Celui qui humilie" },
    { id: 26, arabic: "السَّمِيعُ", transliteration: "As-Sami", meaning: "L'Audient" },
    { id: 27, arabic: "الْبَصِيرُ", transliteration: "Al-Basir", meaning: "Le Clairvoyant" },
    { id: 28, arabic: "الْحَكَمُ", transliteration: "Al-Hakam", meaning: "Le Juge" },
    { id: 29, arabic: "الْعَدْلُ", transliteration: "Al-Adl", meaning: "Le Juste" },
    { id: 30, arabic: "اللَّطِيفُ", transliteration: "Al-Latif", meaning: "Le Subtil Bienveillant" },
    { id: 31, arabic: "الْخَبِيرُ", transliteration: "Al-Khabir", meaning: "Le Parfaitement Informé" },
    { id: 32, arabic: "الْحَلِيمُ", transliteration: "Al-Halim", meaning: "Le Longanime" },
    { id: 33, arabic: "الْعَظِيمُ", transliteration: "Al-Azim", meaning: "L'Immense" },
    { id: 34, arabic: "الْغَفُورُ", transliteration: "Al-Ghafur", meaning: "Le Pardonneur" },
    { id: 35, arabic: "الشَّكُورُ", transliteration: "Ash-Shakur", meaning: "Le Reconnaissant" },
    { id: 36, arabic: "الْعَلِيُّ", transliteration: "Al-Aliyy", meaning: "Le Très Haut" },
    { id: 37, arabic: "الْكَبِيرُ", transliteration: "Al-Kabir", meaning: "Le Grand" },
    { id: 38, arabic: "الْحَفِيظُ", transliteration: "Al-Hafiz", meaning: "Le Gardien" },
    { id: 39, arabic: "المُقيِت", transliteration: "Al-Muqit", meaning: "Le Nourricier" },
    { id: 40, arabic: "اَلْحسِيبُ", transliteration: "Al-Hasib", meaning: "Le Compteur" },
    { id: 41, arabic: "الْجَلِيلُ", transliteration: "Al-Jalil", meaning: "Le Majestueux" },
    { id: 42, arabic: "الْكَرِيمُ", transliteration: "Al-Karim", meaning: "Le Généreux" },
    { id: 43, arabic: "الرَّقِيبُ", transliteration: "Ar-Raqib", meaning: "Le Vigilant" },
    { id: 44, arabic: "الْمُجِيبُ", transliteration: "Al-Mujib", meaning: "Celui qui exauce" },
    { id: 45, arabic: "الْوَاسِعُ", transliteration: "Al-Wasi", meaning: "L'Immense" },
    { id: 46, arabic: "الْحَكِيمُ", transliteration: "Al-Hakim", meaning: "Le Sage" },
    { id: 47, arabic: "الْوَدُودُ", transliteration: "Al-Wadud", meaning: "Le Bien-Aimant" },
    { id: 48, arabic: "الْمَجِيدُ", transliteration: "Al-Majid", meaning: "Le Très Glorieux" },
    { id: 49, arabic: "الْبَاعِثُ", transliteration: "Al-Ba'ith", meaning: "Le Résurrecteur" },
    { id: 50, arabic: "الشَّهِيدُ", transliteration: "Ash-Shahid", meaning: "Le Témoin" },
    { id: 51, arabic: "الْحَقُّ", transliteration: "Al-Haqq", meaning: "La Vérité" },
    { id: 52, arabic: "الْوَكِيلُ", transliteration: "Al-Wakil", meaning: "Le Protecteur" },
    { id: 53, arabic: "الْقَوِيُّ", transliteration: "Al-Qawiyy", meaning: "Le Fort" },
    { id: 54, arabic: "الْمَتِينُ", transliteration: "Al-Matin", meaning: "Le Ferme" },
    { id: 55, arabic: "الْوَلِيُّ", transliteration: "Al-Waliyy", meaning: "L'Ami Protecteur" },
    { id: 56, arabic: "الْحَمِيدُ", transliteration: "Al-Hamid", meaning: "Le Louable" },
    { id: 57, arabic: "الْمُحْصِي", transliteration: "Al-Muhsi", meaning: "Celui qui dénombre" },
    { id: 58, arabic: "الْمُبْدِئُ", transliteration: "Al-Mubdi", meaning: "L'Initiateur" },
    { id: 59, arabic: "الْمُعِيدُ", transliteration: "Al-Mu'id", meaning: "Le Restaurateur" },
    { id: 60, arabic: "الْمُحْيِي", transliteration: "Al-Muhyi", meaning: "Le Vivificateur" },
    { id: 61, arabic: "اَلْمُمِيتُ", transliteration: "Al-Mumit", meaning: "Celui qui fait mourir" },
    { id: 62, arabic: "الْحَيُّ", transliteration: "Al-Hayy", meaning: "Le Vivant" },
    { id: 63, arabic: "الْقَيُّومُ", transliteration: "Al-Qayyum", meaning: "Le Subsistant" },
    { id: 64, arabic: "الْوَاجِدُ", transliteration: "Al-Wajid", meaning: "L'Opulent" },
    { id: 65, arabic: "الْمَاجِدُ", transliteration: "Al-Majid", meaning: "Le Noble" },
    { id: 66, arabic: "الْواحِدُ", transliteration: "Al-Wahid", meaning: "L'Unique" },
    { id: 67, arabic: "اَلاَحَدُ", transliteration: "Al-Ahad", meaning: "L'Un" },
    { id: 68, arabic: "الصَّمَدُ", transliteration: "As-Samad", meaning: "L'Absolu" },
    { id: 69, arabic: "الْقَادِرُ", transliteration: "Al-Qadir", meaning: "Le Capable" },
    { id: 70, arabic: "الْمُقْتَدِرُ", transliteration: "Al-Muqtadir", meaning: "Le Tout Puissant" },
    { id: 71, arabic: "الْمُقَدِّمُ", transliteration: "Al-Muqaddim", meaning: "Celui qui avance" },
    { id: 72, arabic: "الْمُؤَخِّرُ", transliteration: "Al-Mu'akhkhir", meaning: "Celui qui retarde" },
    { id: 73, arabic: "الأوَّلُ", transliteration: "Al-Awwal", meaning: "Le Premier" },
    { id: 74, arabic: "الآخِرُ", transliteration: "Al-Akhir", meaning: "Le Dernier" },
    { id: 75, arabic: "الظَّاهِرُ", transliteration: "Az-Zahir", meaning: "L'Apparent" },
    { id: 76, arabic: "الْبَاطِنُ", transliteration: "Al-Batin", meaning: "Le Caché" },
    { id: 77, arabic: "الْوَالِي", transliteration: "Al-Wali", meaning: "Le Gérant" },
    { id: 78, arabic: "الْمُتَعَالِي", transliteration: "Al-Muta'ali", meaning: "Le Très Élevé" },
    { id: 79, arabic: "الْبَرُّ", transliteration: "Al-Barr", meaning: "Le Bienfaisant" },
    { id: 80, arabic: "التَّوَّابُ", transliteration: "At-Tawwab", meaning: "L'Accueillant au repentir" },
    { id: 81, arabic: "الْمُنْتَقِمُ", transliteration: "Al-Muntaqim", meaning: "Le Vengeur" },
    { id: 82, arabic: "العَفُوُّ", transliteration: "Al-Afuww", meaning: "L'Indulgent" },
    { id: 83, arabic: "الرَّؤُوفُ", transliteration: "Ar-Ra'uf", meaning: "Le Compatissant" },
    { id: 84, arabic: "مَالِكُ الْمُلْكِ", transliteration: "Malik-ul-Mulk", meaning: "Le Possesseur du Royaume" },
    { id: 85, arabic: "ذُوالْجَلاَلِ وَالإكْرَامِ", transliteration: "Dhul-Jalal-wal-Ikram", meaning: "Le Plein de Majesté et de Générosité" },
    { id: 86, arabic: "الْمُقْسِطُ", transliteration: "Al-Muqsit", meaning: "L'Équitable" },
    { id: 87, arabic: "الْجَامِعُ", transliteration: "Al-Jami", meaning: "Le Rassembleur" },
    { id: 88, arabic: "الْغَنِيُّ", transliteration: "Al-Ghaniyy", meaning: "Le Riche" },
    { id: 89, arabic: "الْمُغْنِي", transliteration: "Al-Mughni", meaning: "Celui qui enrichit" },
    { id: 90, arabic: "اَلْمَانِعُ", transliteration: "Al-Mani", meaning: "Celui qui empêche" },
    { id: 91, arabic: "الضَّارَّ", transliteration: "Ad-Darr", meaning: "Celui qui peut nuire" },
    { id: 92, arabic: "النَّافِعُ", transliteration: "An-Nafi", meaning: "Celui qui profite" },
    { id: 93, arabic: "النُّورُ", transliteration: "An-Nur", meaning: "La Lumière" },
    { id: 94, arabic: "الْهَادِي", transliteration: "Al-Hadi", meaning: "Le Guide" },
    { id: 95, arabic: "الْبَدِيعُ", transliteration: "Al-Badi", meaning: "L'Inventeur" },
    { id: 96, arabic: "اَلْبَاقِي", transliteration: "Al-Baqi", meaning: "L'Éternel" },
    { id: 97, arabic: "الْوَارِثُ", transliteration: "Al-Warith", meaning: "L'Héritier" },
    { id: 98, arabic: "الرَّشِيدُ", transliteration: "Ar-Rashid", meaning: "Le Bien-Dirigeant" },
    { id: 99, arabic: "الصَّبُورُ", transliteration: "As-Sabur", meaning: "Le Patient" }
];

// DUAAS ESSENTIELLES
const DUAAS = [
    { id: 1, category: "Réveil", title: "Duaa au réveil", arabic: "الحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ", transliteration: "Alhamdulillahil-ladhi ahyana ba'da ma amatana wa ilayhin-nushur", translation: "Louange à Allah qui nous a rendu la vie après nous avoir fait mourir", source: "Boukhari" },
    { id: 2, category: "Matin", title: "Duaa du matin", arabic: "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ", transliteration: "Asbahna wa asbahal-mulku lillah, walhamdulillah", translation: "Nous voilà au matin et la royauté appartient à Allah", source: "Muslim" },
    { id: 3, category: "Soir", title: "Duaa du soir", arabic: "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ", transliteration: "Amsayna wa amsal-mulku lillah, walhamdulillah", translation: "Nous voilà au soir et la royauté appartient à Allah", source: "Muslim" },
    { id: 4, category: "Sommeil", title: "Duaa avant de dormir", arabic: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا", transliteration: "Bismika Allahumma amutu wa ahya", translation: "C'est en Ton nom, ô Allah, que je meurs et que je vis", source: "Boukhari" },
    { id: 5, category: "Nourriture", title: "Duaa avant de manger", arabic: "بِسْمِ اللَّهِ وَعَلَى بَرَكَةِ اللَّهِ", transliteration: "Bismillahi wa 'ala barakatillah", translation: "Au nom d'Allah et avec la bénédiction d'Allah", source: "Abu Dawud" },
    { id: 6, category: "Nourriture", title: "Duaa après avoir mangé", arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ", transliteration: "Alhamdulillahil-ladhi at'amana wa saqana wa ja'alana muslimin", translation: "Louange à Allah qui nous a nourris, désaltérés et fait musulmans", source: "Abu Dawud" },
    { id: 7, category: "Maison", title: "Duaa en sortant", arabic: "بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ", transliteration: "Bismillahi tawakkaltu 'alallah, wa la hawla wa la quwwata illa billah", translation: "Au nom d'Allah, je place ma confiance en Allah", source: "Abu Dawud" },
    { id: 8, category: "Mosquée", title: "Duaa en entrant à la mosquée", arabic: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ", transliteration: "Allahumma-ftah li abwaba rahmatik", translation: "Ô Allah, ouvre-moi les portes de Ta miséricorde", source: "Muslim" },
    { id: 9, category: "Protection", title: "Duaa de protection", arabic: "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ", transliteration: "Bismillahil-ladhi la yadurru ma'asmihi shay'un fil-ardi wa la fis-sama'", translation: "Au nom d'Allah, avec Qui rien ne peut nuire", source: "Tirmidhi" },
    { id: 10, category: "Pardon", title: "Sayyidul Istighfar", arabic: "اللَّهُمَّ أَنْتَ رَبِّي، لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ", transliteration: "Allahumma Anta Rabbi, la ilaha illa Anta, khalaqtani wa ana 'abduk", translation: "Ô Allah, Tu es mon Seigneur, il n'y a de dieu que Toi", source: "Boukhari" },
    { id: 11, category: "Difficultés", title: "Duaa dans les difficultés", arabic: "لَا إِلَهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ", transliteration: "La ilaha illa Anta, subhanaka inni kuntu minaz-zalimin", translation: "Il n'y a de dieu que Toi, Gloire à Toi, j'étais parmi les injustes", source: "Tirmidhi" },
    { id: 12, category: "Parents", title: "Duaa pour les parents", arabic: "رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا", transliteration: "Rabbi irhamhuma kama rabbayanee saghira", translation: "Seigneur, fais-leur miséricorde comme ils m'ont élevé", source: "Coran 17:24" },
    { id: 13, category: "Études", title: "Duaa pour la science", arabic: "رَبِّ زِدْنِي عِلْمًا", transliteration: "Rabbi zidni 'ilma", translation: "Seigneur, augmente ma science", source: "Coran 20:114" },
    { id: 14, category: "Examen", title: "Duaa avant un examen", arabic: "اللَّهُمَّ لَا سَهْلَ إِلَّا مَا جَعَلْتَهُ سَهْلًا", transliteration: "Allahumma la sahla illa ma ja'altahu sahla", translation: "Ô Allah, rien n'est facile sauf ce que Tu rends facile", source: "Ibn Hibban" },
    { id: 15, category: "Voyage", title: "Duaa du voyage", arabic: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ", transliteration: "Subhanal-ladhi sakhkhara lana hadha wa ma kunna lahu muqrinin", translation: "Gloire à Celui qui a mis ceci à notre service", source: "Abu Dawud" },
    { id: 16, category: "Anxiété", title: "Duaa contre l'anxiété", arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ", transliteration: "Allahumma inni a'udhu bika minal-hammi wal-hazan", translation: "Ô Allah, je cherche refuge contre le souci et la tristesse", source: "Boukhari" },
    { id: 17, category: "Maladie", title: "Duaa pour la guérison", arabic: "اللَّهُمَّ رَبَّ النَّاسِ، أَذْهِبِ الْبَاسَ، اشْفِ أَنْتَ الشَّافِي", transliteration: "Allahumma Rabban-nas, adhhibil-ba's, ishfi Antash-Shafi", translation: "Ô Allah, Seigneur des hommes, éloigne le mal, guéris", source: "Boukhari" },
    { id: 18, category: "Guidée", title: "Duaa pour la guidée", arabic: "اللَّهُمَّ اهْدِنِي وَسَدِّدْنِي", transliteration: "Allahumma-hdini wa saddidni", translation: "Ô Allah, guide-moi et rends-moi droit", source: "Muslim" },
    { id: 19, category: "Paradis", title: "Duaa pour le Paradis", arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْجَنَّةَ وَأَعُوذُ بِكَ مِنَ النَّارِ", transliteration: "Allahumma inni as'alukal-Jannah, wa a'udhu bika minan-Nar", translation: "Ô Allah, je Te demande le Paradis et cherche refuge contre l'Enfer", source: "Abu Dawud" },
    { id: 20, category: "Ramadan", title: "Duaa de la nuit du destin", arabic: "اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي", transliteration: "Allahumma innaka 'Afuwwun tuhibbul-'afwa fa'fu 'anni", translation: "Ô Allah, Tu es Pardonneur, Tu aimes le pardon, pardonne-moi", source: "Tirmidhi" }
];

const DUAA_CATEGORIES = [
    { id: "all", name: "Toutes", icon: "📿" },
    { id: "Réveil", name: "Réveil", icon: "🌅" },
    { id: "Matin", name: "Matin", icon: "☀️" },
    { id: "Soir", name: "Soir", icon: "🌙" },
    { id: "Sommeil", name: "Sommeil", icon: "😴" },
    { id: "Nourriture", name: "Nourriture", icon: "🍽️" },
    { id: "Maison", name: "Maison", icon: "🏠" },
    { id: "Mosquée", name: "Mosquée", icon: "🕌" },
    { id: "Protection", name: "Protection", icon: "🛡️" },
    { id: "Pardon", name: "Pardon", icon: "🤲" },
    { id: "Parents", name: "Parents", icon: "👨‍👩‍👧" },
    { id: "Études", name: "Études", icon: "📚" },
    { id: "Voyage", name: "Voyage", icon: "✈️" },
    { id: "Maladie", name: "Maladie", icon: "🏥" },
    { id: "Guidée", name: "Guidée", icon: "🧭" },
    { id: "Paradis", name: "Paradis", icon: "🌈" },
    { id: "Ramadan", name: "Ramadan", icon: "🌙" }
];

// QUIZ
const QUIZ_CATEGORIES = [
    { id: "quran", name: "Coran", icon: "📖" },
    { id: "hadith", name: "Hadiths", icon: "📜" },
    { id: "fiqh", name: "Fiqh", icon: "⚖️" },
    { id: "history", name: "Histoire", icon: "🏛️" },
    { id: "prophets", name: "Prophètes", icon: "👤" },
    { id: "pillars", name: "Piliers", icon: "🕋" }
];

const QUIZ_LEVELS = [
    { id: "beginner", name: "Débutant", icon: "🌱" },
    { id: "intermediate", name: "Intermédiaire", icon: "🌿" },
    { id: "advanced", name: "Avancé", icon: "🌳" }
];

const QUIZ_QUESTIONS = [
    { id: 1, category: "quran", level: "beginner", question: "Combien de sourates contient le Coran ?", options: ["100", "114", "120", "130"], correct: 1, explanation: "Le Coran contient 114 sourates." },
    { id: 2, category: "quran", level: "beginner", question: "Quelle est la première sourate du Coran ?", options: ["Al-Baqarah", "Al-Fatiha", "Al-Ikhlas", "Ya-Sin"], correct: 1, explanation: "Al-Fatiha est la première sourate." },
    { id: 3, category: "quran", level: "beginner", question: "Quelle est la plus longue sourate ?", options: ["Al-Fatiha", "Al-Imran", "Al-Baqarah", "An-Nisa"], correct: 2, explanation: "Al-Baqarah avec 286 versets." },
    { id: 4, category: "quran", level: "beginner", question: "Quelle sourate équivaut au tiers du Coran ?", options: ["Al-Fatiha", "Al-Ikhlas", "Al-Baqarah", "Ya-Sin"], correct: 1, explanation: "Al-Ikhlas équivaut au tiers du Coran." },
    { id: 5, category: "pillars", level: "beginner", question: "Combien y a-t-il de piliers de l'Islam ?", options: ["3", "4", "5", "6"], correct: 2, explanation: "L'Islam repose sur 5 piliers." },
    { id: 6, category: "pillars", level: "beginner", question: "Quel est le premier pilier de l'Islam ?", options: ["La prière", "La Shahada", "Le jeûne", "La zakat"], correct: 1, explanation: "La Shahada est le premier pilier." },
    { id: 7, category: "pillars", level: "beginner", question: "En quel mois jeûne-t-on ?", options: ["Sha'ban", "Ramadan", "Shawwal", "Dhul Hijja"], correct: 1, explanation: "Le jeûne s'effectue durant Ramadan." },
    { id: 8, category: "history", level: "beginner", question: "En quelle année est né le Prophète ﷺ ?", options: ["570", "571", "580", "590"], correct: 0, explanation: "Le Prophète ﷺ est né en 570." },
    { id: 9, category: "history", level: "beginner", question: "Qui fut le premier calife ?", options: ["Umar", "Uthman", "Ali", "Abu Bakr"], correct: 3, explanation: "Abu Bakr As-Siddiq fut le premier calife." },
    { id: 10, category: "prophets", level: "beginner", question: "Qui est le premier prophète ?", options: ["Ibrahim", "Nuh", "Adam", "Idris"], correct: 2, explanation: "Adam عليه السلام est le premier prophète." },
    { id: 11, category: "prophets", level: "beginner", question: "Qui a construit l'Arche ?", options: ["Ibrahim", "Musa", "Nuh", "Sulayman"], correct: 2, explanation: "Nuh عليه السلام a construit l'Arche." },
    { id: 12, category: "prophets", level: "beginner", question: "Quel prophète a séparé la mer ?", options: ["Nuh", "Ibrahim", "Musa", "Yunus"], correct: 2, explanation: "Musa عليه السلام a séparé la mer." },
    { id: 13, category: "fiqh", level: "beginner", question: "Combien de prières par jour ?", options: ["3", "4", "5", "6"], correct: 2, explanation: "Il y a 5 prières obligatoires par jour." },
    { id: 14, category: "fiqh", level: "beginner", question: "Combien de rak'at pour Fajr ?", options: ["2", "3", "4", "1"], correct: 0, explanation: "Fajr contient 2 rak'at." },
    { id: 15, category: "hadith", level: "beginner", question: "Quel est le recueil le plus authentique ?", options: ["Muslim", "Abu Dawud", "Boukhari", "Tirmidhi"], correct: 2, explanation: "Sahih Al-Boukhari est le plus authentique." },
    { id: 16, category: "quran", level: "intermediate", question: "Quelle sourate est 'le cœur du Coran' ?", options: ["Al-Fatiha", "Al-Baqarah", "Ya-Sin", "Ar-Rahman"], correct: 2, explanation: "Ya-Sin est le cœur du Coran." },
    { id: 17, category: "quran", level: "intermediate", question: "Combien de juz' dans le Coran ?", options: ["20", "25", "30", "40"], correct: 2, explanation: "Le Coran est divisé en 30 juz'." },
    { id: 18, category: "history", level: "intermediate", question: "En quelle année a eu lieu l'Hégire ?", options: ["610", "622", "630", "632"], correct: 1, explanation: "L'Hégire a eu lieu en 622." },
    { id: 19, category: "prophets", level: "intermediate", question: "Combien de prophètes mentionnés dans le Coran ?", options: ["20", "25", "28", "30"], correct: 1, explanation: "25 prophètes sont mentionnés dans le Coran." },
    { id: 20, category: "fiqh", level: "intermediate", question: "Quel est le taux de la zakat ?", options: ["2%", "2.5%", "5%", "10%"], correct: 1, explanation: "Le taux de la zakat est de 2.5%." }
];

// HADITHS DU JOUR
const DAILY_HADITHS = [
    { id: 1, arabic: "إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ", translation: "Les actes ne valent que par les intentions", source: "Boukhari & Muslim", narrator: "Omar" },
    { id: 2, arabic: "خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ", translation: "Le meilleur d'entre vous est celui qui apprend le Coran et l'enseigne", source: "Boukhari", narrator: "Uthman" },
    { id: 3, arabic: "الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ", translation: "Le musulman est celui dont les autres sont à l'abri de sa langue et de sa main", source: "Boukhari & Muslim", narrator: "Abdullah" },
    { id: 4, arabic: "تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ لَكَ صَدَقَةٌ", translation: "Ton sourire au visage de ton frère est une aumône", source: "Tirmidhi", narrator: "Abu Dharr" },
    { id: 5, arabic: "الطُّهُورُ شَطْرُ الإِيمَانِ", translation: "La purification est la moitié de la foi", source: "Muslim", narrator: "Abu Malik" }
];

// TEXTES DES SOURATES COURTES
const SURAH_TEXTS = {
    1: {
        verses: [
            { number: 1, arabic: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ", phonetic: "Bismillahir-Rahmanir-Rahim", translation: "Au nom d'Allah, le Tout Miséricordieux" },
            { number: 2, arabic: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ", phonetic: "Alhamdu lillahi Rabbil-'alamin", translation: "Louange à Allah, Seigneur de l'univers" },
            { number: 3, arabic: "الرَّحْمَٰنِ الرَّحِيمِ", phonetic: "Ar-Rahmanir-Rahim", translation: "Le Tout Miséricordieux, le Très Miséricordieux" },
            { number: 4, arabic: "مَالِكِ يَوْمِ الدِّينِ", phonetic: "Maliki yawmid-Din", translation: "Maître du Jour de la rétribution" },
            { number: 5, arabic: "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ", phonetic: "Iyyaka na'budu wa iyyaka nasta'in", translation: "C'est Toi que nous adorons, c'est Toi dont nous implorons secours" },
            { number: 6, arabic: "اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ", phonetic: "Ihdinas-siratal-mustaqim", translation: "Guide-nous dans le droit chemin" },
            { number: 7, arabic: "صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ", phonetic: "Siratal-ladhina an'amta 'alayhim, ghayril-maghdubi 'alayhim wa lad-dallin", translation: "Le chemin de ceux que Tu as comblés, non des égarés" }
        ]
    },
    112: {
        verses: [
            { number: 1, arabic: "قُلْ هُوَ اللَّهُ أَحَدٌ", phonetic: "Qul Huwa Allahu Ahad", translation: "Dis: 'Il est Allah, Unique'" },
            { number: 2, arabic: "اللَّهُ الصَّمَدُ", phonetic: "Allahus-Samad", translation: "Allah, Le Seul à être imploré" },
            { number: 3, arabic: "لَمْ يَلِدْ وَلَمْ يُولَدْ", phonetic: "Lam yalid wa lam yulad", translation: "Il n'a jamais engendré, n'a pas été engendré" },
            { number: 4, arabic: "وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ", phonetic: "Wa lam yakun lahu kufuwan ahad", translation: "Et nul n'est égal à Lui" }
        ]
    },
    113: {
        verses: [
            { number: 1, arabic: "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ", phonetic: "Qul a'udhu bi Rabbil-falaq", translation: "Dis: 'Je cherche protection auprès du Seigneur de l'aube'" },
            { number: 2, arabic: "مِن شَرِّ مَا خَلَقَ", phonetic: "Min sharri ma khalaq", translation: "Contre le mal de ce qu'Il a créé" },
            { number: 3, arabic: "وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ", phonetic: "Wa min sharri ghasiqin idha waqab", translation: "Contre le mal de l'obscurité" },
            { number: 4, arabic: "وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ", phonetic: "Wa min sharrin-naffathati fil-'uqad", translation: "Contre le mal des sorcières" },
            { number: 5, arabic: "وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ", phonetic: "Wa min sharri hasidin idha hasad", translation: "Contre le mal de l'envieux" }
        ]
    },
    114: {
        verses: [
            { number: 1, arabic: "قُلْ أَعُوذُ بِرَبِّ النَّاسِ", phonetic: "Qul a'udhu bi Rabbin-nas", translation: "Dis: 'Je cherche protection auprès du Seigneur des hommes'" },
            { number: 2, arabic: "مَلِكِ النَّاسِ", phonetic: "Malikin-nas", translation: "Le Souverain des hommes" },
            { number: 3, arabic: "إِلَٰهِ النَّاسِ", phonetic: "Ilahin-nas", translation: "Dieu des hommes" },
            { number: 4, arabic: "مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ", phonetic: "Min sharril-waswasil-khannas", translation: "Contre le mal du tentateur furtif" },
            { number: 5, arabic: "الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ", phonetic: "Alladhi yuwaswisu fi sudurin-nas", translation: "Qui souffle le mal dans les poitrines" },
            { number: 6, arabic: "مِنَ الْجِنَّةِ وَالنَّاسِ", phonetic: "Minal-jinnati wan-nas", translation: "Qu'il soit djinn ou humain" }
        ]
    }
};

// PROGRAMMES D'APPRENTISSAGE
const LEARNING_PROGRAMS = [
    { id: "10days", name: "Express - 10 jours", duration: 10, description: "Programme intensif" },
    { id: "1month", name: "Standard - 1 mois", duration: 30, description: "Rythme équilibré" },
    { id: "3months", name: "Approfondi - 3 mois", duration: 90, description: "Apprentissage complet" },
    { id: "6months", name: "Maîtrise - 6 mois", duration: 180, description: "Devenir expert" },
    { id: "1year", name: "Excellence - 1 an", duration: 365, description: "Programme complet" },
    { id: "2years", name: "Érudit - 2 ans", duration: 730, description: "Maîtrise totale" }
];

// ALPHABET ARABE
const ARABIC_ALPHABET = [
    { letter: "ا", name: "Alif", transliteration: "a" },
    { letter: "ب", name: "Ba", transliteration: "b" },
    { letter: "ت", name: "Ta", transliteration: "t" },
    { letter: "ث", name: "Tha", transliteration: "th" },
    { letter: "ج", name: "Jim", transliteration: "j" },
    { letter: "ح", name: "Ha", transliteration: "ḥ" },
    { letter: "خ", name: "Kha", transliteration: "kh" },
    { letter: "د", name: "Dal", transliteration: "d" },
    { letter: "ذ", name: "Dhal", transliteration: "dh" },
    { letter: "ر", name: "Ra", transliteration: "r" },
    { letter: "ز", name: "Zay", transliteration: "z" },
    { letter: "س", name: "Sin", transliteration: "s" },
    { letter: "ش", name: "Shin", transliteration: "sh" },
    { letter: "ص", name: "Sad", transliteration: "ṣ" },
    { letter: "ض", name: "Dad", transliteration: "ḍ" },
    { letter: "ط", name: "Ta", transliteration: "ṭ" },
    { letter: "ظ", name: "Za", transliteration: "ẓ" },
    { letter: "ع", name: "Ayn", transliteration: "'" },
    { letter: "غ", name: "Ghayn", transliteration: "gh" },
    { letter: "ف", name: "Fa", transliteration: "f" },
    { letter: "ق", name: "Qaf", transliteration: "q" },
    { letter: "ك", name: "Kaf", transliteration: "k" },
    { letter: "ل", name: "Lam", transliteration: "l" },
    { letter: "م", name: "Mim", transliteration: "m" },
    { letter: "ن", name: "Nun", transliteration: "n" },
    { letter: "ه", name: "Ha", transliteration: "h" },
    { letter: "و", name: "Waw", transliteration: "w/u" },
    { letter: "ي", name: "Ya", transliteration: "y/i" }
];

// COURS D'ARABE
const ARABIC_COURSES = [
    { id: 1, title: "L'Alphabet Arabe", description: "Apprendre les 28 lettres", level: "débutant", duration: "2 semaines", lessons: 7 },
    { id: 2, title: "Les Voyelles", description: "Maîtriser les harakaat", level: "débutant", duration: "1 semaine", lessons: 4 },
    { id: 3, title: "Lecture du Coran", description: "Tajwid de base", level: "débutant", duration: "4 semaines", lessons: 5 },
    { id: 4, title: "Vocabulaire Islamique", description: "Mots essentiels", level: "débutant", duration: "3 semaines", lessons: 4 },
    { id: 5, title: "Grammaire Arabe", description: "Introduction au Nahw", level: "intermédiaire", duration: "6 semaines", lessons: 6 }
];
