import Foundation

struct QuizData {
    static func questions(for difficulty: String) -> [QuizQuestion] {
        let diff: QuizQuestion.QuizDifficulty
        switch difficulty.lowercased() {
        case "easy", "facile": diff = .facile
        case "medium", "moyen": diff = .moyen
        case "hard", "difficile": diff = .difficile
        default: diff = .facile
        }
        return allQuestions.filter { $0.difficulty == diff }
    }

    static let allQuestions: [QuizQuestion] = [
        // MARK: - FACILE
        QuizQuestion(id: "q001", question: "Combien de sourates contient le Coran ?", options: ["100", "114", "120", "99"], correctIndex: 1, explanation: "Le Coran contient 114 sourates.", difficulty: .facile, category: "Coran"),
        QuizQuestion(id: "q002", question: "Quelle est la première sourate du Coran ?", options: ["Al-Baqara", "Al-Ikhlas", "Al-Fatiha", "Yasin"], correctIndex: 2, explanation: "Al-Fatiha est la première sourate.", difficulty: .facile, category: "Coran"),
        QuizQuestion(id: "q003", question: "Combien de versets contient Al-Fatiha ?", options: ["5", "6", "7", "8"], correctIndex: 2, explanation: "Al-Fatiha contient 7 versets.", difficulty: .facile, category: "Coran"),
        QuizQuestion(id: "q004", question: "Quelle est la plus longue sourate du Coran ?", options: ["Al-Imran", "Al-Baqara", "An-Nisa", "Al-Maidah"], correctIndex: 1, explanation: "Al-Baqara est la plus longue sourate avec 286 versets.", difficulty: .facile, category: "Coran"),
        QuizQuestion(id: "q005", question: "Combien de piliers compte l'Islam ?", options: ["3", "4", "5", "6"], correctIndex: 2, explanation: "L'Islam repose sur 5 piliers.", difficulty: .facile, category: "Piliers"),
        QuizQuestion(id: "q006", question: "Quel est le premier pilier de l'Islam ?", options: ["La Salat", "La Zakat", "La Shahada", "Le Hajj"], correctIndex: 2, explanation: "La Shahada est la profession de foi.", difficulty: .facile, category: "Piliers"),
        QuizQuestion(id: "q007", question: "Combien de fois par jour un musulman prie-t-il ?", options: ["3", "4", "5", "6"], correctIndex: 2, explanation: "Un musulman prie 5 fois par jour.", difficulty: .facile, category: "Piliers"),
        QuizQuestion(id: "q008", question: "Quel est le mois de jeûne en Islam ?", options: ["Rajab", "Ramadan", "Chawwal", "Dhul Hijja"], correctIndex: 1, explanation: "Le Ramadan est le 9ème mois du calendrier islamique.", difficulty: .facile, category: "Piliers"),
        QuizQuestion(id: "q009", question: "Vers quelle ville les musulmans se tournent-ils pour prier ?", options: ["Médine", "Jérusalem", "La Mecque", "Baghdad"], correctIndex: 2, explanation: "La Qibla est en direction de La Mecque.", difficulty: .facile, category: "Piliers"),
        QuizQuestion(id: "q010", question: "Comment s'appelle le pèlerinage islamique ?", options: ["Umrah", "Hajj", "Zakat", "Salat"], correctIndex: 1, explanation: "Le Hajj est le 5ème pilier de l'Islam.", difficulty: .facile, category: "Piliers"),
        QuizQuestion(id: "q011", question: "Quel est le nom du Prophète de l'Islam ?", options: ["Ibrahim", "Moussa", "Muhammad", "Issa"], correctIndex: 2, explanation: "Muhammad ﷺ est le dernier prophète.", difficulty: .facile, category: "Prophètes"),
        QuizQuestion(id: "q012", question: "Dans quelle ville est né le Prophète Muhammad ﷺ ?", options: ["Médine", "La Mecque", "Taïf", "Jérusalem"], correctIndex: 1, explanation: "Le Prophète ﷺ est né à La Mecque.", difficulty: .facile, category: "Prophètes"),
        QuizQuestion(id: "q013", question: "Quel est le premier prophète mentionné dans le Coran ?", options: ["Noé", "Adam", "Ibrahim", "Moussa"], correctIndex: 1, explanation: "Adam est le premier homme et prophète.", difficulty: .facile, category: "Prophètes"),
        QuizQuestion(id: "q014", question: "Combien de prophètes sont mentionnés dans le Coran ?", options: ["15", "20", "25", "30"], correctIndex: 2, explanation: "25 prophètes sont mentionnés dans le Coran.", difficulty: .facile, category: "Prophètes"),
        QuizQuestion(id: "q015", question: "Comment s'appelle la femme du Prophète ﷺ surnommée 'Mère des croyants' ?", options: ["Fatima", "Khadija", "Aïcha", "Hafsa"], correctIndex: 1, explanation: "Khadija fut la première épouse du Prophète ﷺ.", difficulty: .facile, category: "Prophètes"),
        QuizQuestion(id: "q016", question: "Qu'est-ce que la Zakat ?", options: ["Le jeûne", "La prière", "L'aumône légale", "Le pèlerinage"], correctIndex: 2, explanation: "La Zakat est l'aumône obligatoire.", difficulty: .facile, category: "Piliers"),
        QuizQuestion(id: "q017", question: "Quel est le livre sacré de l'Islam ?", options: ["La Torah", "L'Injil", "Le Coran", "Le Zabour"], correctIndex: 2, explanation: "Le Coran est le livre sacré de l'Islam.", difficulty: .facile, category: "Coran"),
        QuizQuestion(id: "q018", question: "Comment s'appelle la prière du vendredi ?", options: ["Salat al-Asr", "Salat al-Jumu'a", "Salat al-Fajr", "Salat al-Isha"], correctIndex: 1, explanation: "Salat al-Jumu'a est la prière du vendredi.", difficulty: .facile, category: "Pratiques"),
        QuizQuestion(id: "q019", question: "Qu'est-ce que le Dhikr ?", options: ["La prière", "Le souvenir d'Allah", "Le jeûne", "La charité"], correctIndex: 1, explanation: "Le Dhikr est la mention et le souvenir d'Allah.", difficulty: .facile, category: "Dhikr"),
        QuizQuestion(id: "q020", question: "Que signifie 'Alhamdulillah' ?", options: ["Dieu est grand", "Louange à Allah", "Au nom d'Allah", "Allah est unique"], correctIndex: 1, explanation: "Alhamdulillah signifie 'Louange à Allah'.", difficulty: .facile, category: "Dhikr"),
        QuizQuestion(id: "q021", question: "Que signifie 'Allahu Akbar' ?", options: ["Allah est unique", "Allah est miséricordieux", "Allah est le plus grand", "Pas de divinité sauf Allah"], correctIndex: 2, explanation: "Allahu Akbar signifie 'Allah est le plus grand'.", difficulty: .facile, category: "Dhikr"),
        QuizQuestion(id: "q022", question: "Que signifie 'SubhanAllah' ?", options: ["Gloire à Allah", "Allah est grand", "Louange à Allah", "Merci Allah"], correctIndex: 0, explanation: "SubhanAllah signifie 'Gloire à Allah'.", difficulty: .facile, category: "Dhikr"),
        QuizQuestion(id: "q023", question: "Comment s'appelle la direction de la prière ?", options: ["Mirhab", "Minbar", "Qibla", "Adhan"], correctIndex: 2, explanation: "La Qibla est la direction vers La Mecque.", difficulty: .facile, category: "Pratiques"),
        QuizQuestion(id: "q024", question: "Comment s'appelle l'appel à la prière ?", options: ["Iqama", "Adhan", "Salat", "Takbir"], correctIndex: 1, explanation: "L'Adhan est l'appel à la prière.", difficulty: .facile, category: "Pratiques"),
        QuizQuestion(id: "q025", question: "Qu'est-ce que le Wudhu ?", options: ["La prière", "L'ablution", "Le jeûne", "La charité"], correctIndex: 1, explanation: "Le Wudhu est la purification rituelle avant la prière.", difficulty: .facile, category: "Pratiques"),
        QuizQuestion(id: "q026", question: "Combien de rakats contient la prière de Fajr ?", options: ["2", "3", "4", "5"], correctIndex: 0, explanation: "La prière de Fajr contient 2 rakats obligatoires.", difficulty: .facile, category: "Pratiques"),
        QuizQuestion(id: "q027", question: "Quelle est la plus courte sourate du Coran ?", options: ["Al-Ikhlas", "Al-Kawthar", "Al-Asr", "Al-Falaq"], correctIndex: 1, explanation: "Al-Kawthar est la plus courte sourate avec 3 versets.", difficulty: .facile, category: "Coran"),
        QuizQuestion(id: "q028", question: "Que signifie 'Islam' ?", options: ["La paix", "La soumission", "La foi", "La prière"], correctIndex: 1, explanation: "Islam signifie soumission à la volonté d'Allah.", difficulty: .facile, category: "Vocabulaire"),
        QuizQuestion(id: "q029", question: "Comment s'appelle un musulman qui a mémorisé le Coran ?", options: ["Mufti", "Imam", "Hafiz", "Qadi"], correctIndex: 2, explanation: "Un Hafiz est celui qui a mémorisé le Coran.", difficulty: .facile, category: "Vocabulaire"),
        QuizQuestion(id: "q030", question: "Dans quel pays se trouve La Mecque ?", options: ["Égypte", "Jordanie", "Arabie Saoudite", "Iran"], correctIndex: 2, explanation: "La Mecque se trouve en Arabie Saoudite.", difficulty: .facile, category: "Géographie"),

        // MARK: - MOYEN
        QuizQuestion(id: "q031", question: "En quelle année a eu lieu l'Hégire ?", options: ["610", "622", "632", "640"], correctIndex: 1, explanation: "L'Hégire a eu lieu en 622 ap. J.-C.", difficulty: .moyen, category: "Histoire"),
        QuizQuestion(id: "q032", question: "Qui fut le premier calife après le Prophète ﷺ ?", options: ["Omar ibn al-Khattab", "Ali ibn Abi Talib", "Abu Bakr as-Siddiq", "Uthman ibn Affan"], correctIndex: 2, explanation: "Abu Bakr as-Siddiq fut le premier calife.", difficulty: .moyen, category: "Histoire"),
        QuizQuestion(id: "q033", question: "Combien de versets contient le Coran ?", options: ["6236", "6000", "6666", "6500"], correctIndex: 0, explanation: "Le Coran contient 6236 versets.", difficulty: .moyen, category: "Coran"),
        QuizQuestion(id: "q034", question: "Quel est le nom de la mère du Prophète ﷺ ?", options: ["Fatima", "Khadija", "Amina", "Halima"], correctIndex: 2, explanation: "La mère du Prophète ﷺ s'appelait Amina bint Wahb.", difficulty: .moyen, category: "Prophètes"),
        QuizQuestion(id: "q035", question: "Quelle sourate est appelée 'le cœur du Coran' ?", options: ["Al-Fatiha", "Al-Baqara", "Yasin", "Al-Kahf"], correctIndex: 2, explanation: "Yasin est souvent appelée le cœur du Coran.", difficulty: .moyen, category: "Coran"),
        QuizQuestion(id: "q036", question: "Combien d'années a duré la révélation du Coran ?", options: ["10 ans", "15 ans", "20 ans", "23 ans"], correctIndex: 3, explanation: "La révélation a duré 23 ans.", difficulty: .moyen, category: "Coran"),
        QuizQuestion(id: "q037", question: "Quel compagnon est surnommé 'Al-Farouq' ?", options: ["Abu Bakr", "Omar ibn al-Khattab", "Ali ibn Abi Talib", "Uthman"], correctIndex: 1, explanation: "Omar ibn al-Khattab est surnommé Al-Farouq.", difficulty: .moyen, category: "Compagnons"),
        QuizQuestion(id: "q038", question: "Quelle est la signification de 'Inshallah' ?", options: ["Dieu merci", "Si Dieu le veut", "Dieu est grand", "Au nom de Dieu"], correctIndex: 1, explanation: "Inshallah signifie 'Si Allah le veut'.", difficulty: .moyen, category: "Vocabulaire"),
        QuizQuestion(id: "q039", question: "Quel est le nom du père d'Ibrahim (AS) ?", options: ["Azar", "Noé", "Houd", "Salih"], correctIndex: 0, explanation: "Le père d'Ibrahim (AS) s'appelait Azar.", difficulty: .moyen, category: "Prophètes"),
        QuizQuestion(id: "q040", question: "Quelle est la nuit la plus sacrée du Ramadan ?", options: ["Laylat al-Mi'raj", "Laylat al-Qadr", "Laylat al-Bara'a", "Laylat al-Isra"], correctIndex: 1, explanation: "Laylat al-Qadr est meilleure que mille mois.", difficulty: .moyen, category: "Pratiques"),
        QuizQuestion(id: "q041", question: "Combien de juz' contient le Coran ?", options: ["20", "25", "30", "114"], correctIndex: 2, explanation: "Le Coran est divisé en 30 juz'.", difficulty: .moyen, category: "Coran"),
        QuizQuestion(id: "q042", question: "Quelle école juridique a fondé l'imam Malik ?", options: ["Hanafite", "Malikite", "Shafiite", "Hanbalite"], correctIndex: 1, explanation: "L'imam Malik a fondé l'école Malikite.", difficulty: .moyen, category: "Jurisprudence"),
        QuizQuestion(id: "q043", question: "Comment s'appelle le trajet nocturne du Prophète ﷺ ?", options: ["Al-Mi'raj", "Al-Isra", "Al-Isra wal Mi'raj", "Al-Hijra"], correctIndex: 2, explanation: "Al-Isra wal Mi'raj est le voyage nocturne et l'ascension.", difficulty: .moyen, category: "Histoire"),
        QuizQuestion(id: "q044", question: "Quel est le nombre de Noms d'Allah mentionnés dans le hadith ?", options: ["33", "66", "99", "100"], correctIndex: 2, explanation: "Allah a 99 beaux noms (Al-Asma al-Husna).", difficulty: .moyen, category: "Noms d'Allah"),
        QuizQuestion(id: "q045", question: "Quel prophète fut avalé par une baleine ?", options: ["Issa", "Moussa", "Yousuf", "Younous"], correctIndex: 3, explanation: "Younous (Jonas) fut avalé par une grande baleine.", difficulty: .moyen, category: "Prophètes"),
        QuizQuestion(id: "q046", question: "Comment s'appelle la femme de Pharaon qui crut en Moussa ?", options: ["Balkis", "Assia", "Maryam", "Sara"], correctIndex: 1, explanation: "Assia bint Muzahim est une des meilleures femmes du paradis.", difficulty: .moyen, category: "Histoire"),
        QuizQuestion(id: "q047", question: "Qu'est-ce que la Sira ?", options: ["La jurisprudence islamique", "La biographie du Prophète ﷺ", "Les hadiths", "La théologie"], correctIndex: 1, explanation: "La Sira est la biographie du Prophète Muhammad ﷺ.", difficulty: .moyen, category: "Sciences islamiques"),
        QuizQuestion(id: "q048", question: "Dans quelle ville se trouve la mosquée Al-Aqsa ?", options: ["La Mecque", "Médine", "Jérusalem", "Baghdad"], correctIndex: 2, explanation: "Al-Aqsa se trouve à Jérusalem.", difficulty: .moyen, category: "Géographie"),
        QuizQuestion(id: "q049", question: "Quel est le nom du premier muezzin de l'Islam ?", options: ["Abu Bakr", "Bilal ibn Rabah", "Omar", "Salman"], correctIndex: 1, explanation: "Bilal ibn Rabah fut le premier muezzin.", difficulty: .moyen, category: "Compagnons"),
        QuizQuestion(id: "q050", question: "Combien de fois le mot 'Salat' apparaît dans le Coran ?", options: ["5", "67", "99", "114"], correctIndex: 1, explanation: "Le mot Salat apparaît 67 fois dans le Coran.", difficulty: .moyen, category: "Coran"),
        QuizQuestion(id: "q051", question: "Quelle est la capitale historique de l'empire abbasside ?", options: ["Damas", "Baghdad", "Le Caire", "Cordoue"], correctIndex: 1, explanation: "Baghdad fut la capitale de l'empire abbasside.", difficulty: .moyen, category: "Civilisation"),
        QuizQuestion(id: "q052", question: "Quel est l'autre nom de La Mecque mentionné dans le Coran ?", options: ["Al-Quds", "Bakka", "Yathrib", "Madinah"], correctIndex: 1, explanation: "La Mecque est aussi appelée Bakka dans le Coran.", difficulty: .moyen, category: "Géographie"),
        QuizQuestion(id: "q053", question: "Quel compagnon est surnommé 'Dhul Nurayn' ?", options: ["Abu Bakr", "Omar", "Uthman", "Ali"], correctIndex: 2, explanation: "Uthman ibn Affan est surnommé Dhul Nurayn car il épousa deux filles du Prophète ﷺ.", difficulty: .moyen, category: "Compagnons"),
        QuizQuestion(id: "q054", question: "Qu'est-ce que le Tawhid ?", options: ["La jurisprudence", "L'unicité d'Allah", "La prière", "La charité"], correctIndex: 1, explanation: "Le Tawhid est le principe fondamental de l'unicité d'Allah.", difficulty: .moyen, category: "Théologie"),
        QuizQuestion(id: "q055", question: "Quel imam a compilé le Sahih Bukhari ?", options: ["Imam Muslim", "Imam Bukhari", "Imam Ahmad", "Imam Malik"], correctIndex: 1, explanation: "L'imam Bukhari a compilé le Sahih Bukhari.", difficulty: .moyen, category: "Hadith"),
        QuizQuestion(id: "q056", question: "Qu'est-ce que la Fitna ?", options: ["La charité", "L'épreuve ou la discorde", "La prière", "Le pèlerinage"], correctIndex: 1, explanation: "La Fitna désigne l'épreuve, la tentation ou la discorde.", difficulty: .moyen, category: "Vocabulaire"),
        QuizQuestion(id: "q057", question: "Quel est le surnom d'Abu Bakr as-Siddiq ?", options: ["Al-Farouq", "As-Siddiq", "Al-Amin", "Dhul Nurayn"], correctIndex: 1, explanation: "As-Siddiq signifie 'le véridique'.", difficulty: .moyen, category: "Compagnons"),
        QuizQuestion(id: "q058", question: "Dans quelle ville le Prophète ﷺ est-il enterré ?", options: ["La Mecque", "Médine", "Jérusalem", "Taïf"], correctIndex: 1, explanation: "Le Prophète ﷺ est enterré à Médine.", difficulty: .moyen, category: "Géographie"),
        QuizQuestion(id: "q059", question: "Quel est le nom du fils d'Ibrahim (AS) qu'il allait sacrifier ?", options: ["Ismail", "Ishaq", "Yaqoub", "Yousuf"], correctIndex: 0, explanation: "Ismail (AS) fut le fils qu'Ibrahim devait sacrifier selon la majorité des savants.", difficulty: .moyen, category: "Prophètes"),
        QuizQuestion(id: "q060", question: "Qu'est-ce que la Sunnah ?", options: ["Les versets coraniques", "Les paroles et actes du Prophète ﷺ", "La jurisprudence", "La théologie"], correctIndex: 1, explanation: "La Sunnah comprend les paroles, actes et approbations du Prophète ﷺ.", difficulty: .moyen, category: "Sciences islamiques"),

        // MARK: - DIFFICILE
        QuizQuestion(id: "q061", question: "Combien de sciences coraniques (Ulum al-Quran) existent ?", options: ["10", "20", "77", "Plus de 80"], correctIndex: 3, explanation: "Certains savants recensent plus de 80 sciences coraniques.", difficulty: .difficile, category: "Ulum al-Quran"),
        QuizQuestion(id: "q062", question: "Qu'est-ce que le 'Nasikh' dans les sciences coraniques ?", options: ["Le verset abrogatif", "Le verset abrogé", "Le verset ambigu", "Le verset clair"], correctIndex: 0, explanation: "Le Nasikh est le verset qui abroge un autre verset.", difficulty: .difficile, category: "Ulum al-Quran"),
        QuizQuestion(id: "q063", question: "Quel est le terme pour les versets dont le sens est clair ?", options: ["Mutashabih", "Muhkam", "Mujmal", "Mubham"], correctIndex: 1, explanation: "Les versets Muhkam sont ceux dont le sens est clair et précis.", difficulty: .difficile, category: "Ulum al-Quran"),
        QuizQuestion(id: "q064", question: "Qu'est-ce que l'Ijaz du Coran ?", options: ["La mémorisation", "L'inimitabilité du Coran", "La récitation", "La traduction"], correctIndex: 1, explanation: "L'Ijaz est le caractère inimitable et miraculeux du Coran.", difficulty: .difficile, category: "Ulum al-Quran"),
        QuizQuestion(id: "q065", question: "Quel savant a écrit 'Al-Itqan fi Ulum al-Quran' ?", options: ["Ibn Taymiyya", "As-Suyuti", "Al-Ghazali", "Ibn Kathir"], correctIndex: 1, explanation: "Jalal al-Din as-Suyuti a écrit Al-Itqan fi Ulum al-Quran.", difficulty: .difficile, category: "Ulum al-Quran"),
        QuizQuestion(id: "q066", question: "Qu'est-ce que le 'Isnad' dans la science du hadith ?", options: ["Le texte du hadith", "La chaîne de transmission", "La critique du hadith", "Le recueil de hadiths"], correctIndex: 1, explanation: "L'Isnad est la chaîne de transmission des rapporteurs du hadith.", difficulty: .difficile, category: "Hadith"),
        QuizQuestion(id: "q067", question: "Qu'est-ce qu'un hadith 'Mutawatir' ?", options: ["Hadith rapporté par un seul", "Hadith faible", "Hadith transmis par un grand nombre à chaque génération", "Hadith inventé"], correctIndex: 2, explanation: "Un hadith Mutawatir est transmis par suffisamment de rapporteurs pour exclure toute fabrication.", difficulty: .difficile, category: "Hadith"),
        QuizQuestion(id: "q068", question: "Qu'est-ce que l'école Ash'ariyya ?", options: ["Une école de droit", "Une école de théologie islamique", "Une école de soufisme", "Une école de hadith"], correctIndex: 1, explanation: "L'Ash'ariyya est une école de théologie fondée par Al-Ash'ari.", difficulty: .difficile, category: "Théologie"),
        QuizQuestion(id: "q069", question: "Qu'est-ce que le 'Fiqh al-Aqalliyyat' ?", options: ["Jurisprudence des majorités", "Jurisprudence des minorités musulmanes", "Jurisprudence comparée", "Jurisprudence classique"], correctIndex: 1, explanation: "Le Fiqh al-Aqalliyyat traite des questions juridiques des musulmans vivant en minorité.", difficulty: .difficile, category: "Jurisprudence"),
        QuizQuestion(id: "q070", question: "Quel est le terme pour l'effort d'interprétation juridique indépendant ?", options: ["Taqlid", "Ijtihad", "Ijma", "Qiyas"], correctIndex: 1, explanation: "L'Ijtihad est l'effort intellectuel pour déduire des règles juridiques.", difficulty: .difficile, category: "Jurisprudence"),
        QuizQuestion(id: "q071", question: "Qu'est-ce que le 'Maqasid al-Sharia' ?", options: ["Les sources de la loi", "Les finalités et objectifs de la loi islamique", "Les interdits islamiques", "Les obligations islamiques"], correctIndex: 1, explanation: "Les Maqasid al-Sharia sont les objectifs supérieurs de la loi islamique.", difficulty: .difficile, category: "Jurisprudence"),
        QuizQuestion(id: "q072", question: "Combien de Maqasid fondamentaux identifie Al-Ghazali ?", options: ["3", "4", "5", "6"], correctIndex: 2, explanation: "Al-Ghazali identifie 5 Maqasid : la religion, la vie, l'intellect, la descendance et les biens.", difficulty: .difficile, category: "Jurisprudence"),
        QuizQuestion(id: "q073", question: "Qu'est-ce que la 'Khalwa' en soufisme ?", options: ["La méditation collective", "La retraite spirituelle solitaire", "La récitation du Coran", "Le jeûne volontaire"], correctIndex: 1, explanation: "La Khalwa est une retraite spirituelle dans la tradition soufie.", difficulty: .difficile, category: "Soufisme"),
        QuizQuestion(id: "q074", question: "Quel philosophe musulman est l'auteur de 'Tahafut al-Falasifa' ?", options: ["Ibn Rushd", "Ibn Sina", "Al-Ghazali", "Al-Farabi"], correctIndex: 2, explanation: "Al-Ghazali a écrit 'L'incohérence des philosophes'.", difficulty: .difficile, category: "Philosophie"),
        QuizQuestion(id: "q075", question: "Qu'est-ce que le 'Kashf' en terminologie soufie ?", options: ["La purification", "La révélation mystique ou dévoilement spirituel", "La méditation", "La pénitence"], correctIndex: 1, explanation: "Le Kashf est le dévoilement spirituel dans la voie soufie.", difficulty: .difficile, category: "Soufisme"),
        QuizQuestion(id: "q076", question: "Qu'est-ce que la science du 'Tajwid' ?", options: ["La mémorisation du Coran", "Les règles de récitation du Coran", "La traduction du Coran", "L'exégèse coranique"], correctIndex: 1, explanation: "Le Tajwid est la science des règles de récitation du Coran.", difficulty: .difficile, category: "Ulum al-Quran"),
        QuizQuestion(id: "q077", question: "Quel est le premier niveau de la certitude selon les soufis ?", options: ["Haqq al-Yaqin", "Ayn al-Yaqin", "Ilm al-Yaqin", "Nur al-Yaqin"], correctIndex: 2, explanation: "Ilm al-Yaqin (la science de la certitude) est le premier niveau.", difficulty: .difficile, category: "Soufisme"),
        QuizQuestion(id: "q078", question: "Qu'est-ce que le 'Talaq' en jurisprudence islamique ?", options: ["Le mariage", "Le divorce", "La dot", "La tutelle"], correctIndex: 1, explanation: "Le Talaq est la répudiation ou le divorce en droit islamique.", difficulty: .difficile, category: "Jurisprudence"),
        QuizQuestion(id: "q079", question: "Quel savant a fondé la méthode du 'Tafsir bil-Ma'thur' ?", options: ["Ibn Abbas", "At-Tabari", "Ibn Kathir", "As-Suyuti"], correctIndex: 1, explanation: "At-Tabari a fondé la méthode d'exégèse par les traditions transmises.", difficulty: .difficile, category: "Ulum al-Quran"),
        QuizQuestion(id: "q080", question: "Qu'est-ce que l''Ijma' en jurisprudence islamique ?", options: ["L'analogie juridique", "Le consensus des savants", "L'opinion individuelle", "La source textuelle"], correctIndex: 1, explanation: "L'Ijma est le consensus des savants musulmans sur une question juridique.", difficulty: .difficile, category: "Jurisprudence"),
        QuizQuestion(id: "q081", question: "Qu'est-ce que le 'Barzakh' ?", options: ["Le paradis", "L'enfer", "Le monde intermédiaire entre la mort et la résurrection", "Le jour du jugement"], correctIndex: 2, explanation: "Le Barzakh est l'état intermédiaire entre la mort et la résurrection.", difficulty: .difficile, category: "Eschatologie"),
        QuizQuestion(id: "q082", question: "Combien de trompettes sonnera l'ange Israfil ?", options: ["1", "2", "3", "4"], correctIndex: 1, explanation: "Israfil sonnera deux fois de la trompette.", difficulty: .difficile, category: "Eschatologie"),
        QuizQuestion(id: "q083", question: "Qu'est-ce que le 'Sirat' eschatologique ?", options: ["Le livre des actions", "Le pont au-dessus de l'enfer", "La balance des actes", "L'intercession"], correctIndex: 1, explanation: "Le Sirat est le pont placé au-dessus de la géhenne que traverseront les âmes.", difficulty: .difficile, category: "Eschatologie"),
        QuizQuestion(id: "q084", question: "Qu'est-ce que le 'Kalam' islamique ?", options: ["Les hadiths", "La théologie dialectique islamique", "La jurisprudence", "L'exégèse"], correctIndex: 1, explanation: "Le Kalam est la théologie rationnelle et dialectique islamique.", difficulty: .difficile, category: "Théologie"),
        QuizQuestion(id: "q085", question: "Quel terme désigne l'exégèse coranique par l'opinion ?", options: ["Tafsir bil-Ma'thur", "Tafsir bil-Ra'y", "Tafsir Ishari", "Tafsir Ilmi"], correctIndex: 1, explanation: "Le Tafsir bil-Ra'y est l'interprétation basée sur l'opinion et la raison.", difficulty: .difficile, category: "Ulum al-Quran"),
        QuizQuestion(id: "q086", question: "Qu'est-ce que la 'Nafs al-Ammara' ?", options: ["L'âme apaisée", "L'âme blâmante", "L'âme qui incite au mal", "L'âme inspirée"], correctIndex: 2, explanation: "La Nafs al-Ammara est l'âme qui incite au mal, mentionnée dans le Coran.", difficulty: .difficile, category: "Soufisme"),
        QuizQuestion(id: "q087", question: "Quel philosophe a écrit 'Hayy ibn Yaqzan' ?", options: ["Al-Ghazali", "Ibn Tufayl", "Ibn Rushd", "Ibn Sina"], correctIndex: 1, explanation: "Ibn Tufayl a écrit ce roman philosophique islamique.", difficulty: .difficile, category: "Philosophie"),
        QuizQuestion(id: "q088", question: "Qu'est-ce que le 'Tazkiyat al-Nafs' ?", options: ["La récitation du Coran", "La purification de l'âme", "L'apprentissage du fiqh", "Le pèlerinage"], correctIndex: 1, explanation: "Le Tazkiyat al-Nafs est la purification et le développement de l'âme.", difficulty: .difficile, category: "Soufisme"),
        QuizQuestion(id: "q089", question: "Qu'est-ce que le 'Qiyas' en jurisprudence ?", options: ["Le consensus", "Le raisonnement par analogie", "L'intérêt public", "La coutume"], correctIndex: 1, explanation: "Le Qiyas est le raisonnement par analogie, 4ème source du droit islamique.", difficulty: .difficile, category: "Jurisprudence"),
        QuizQuestion(id: "q090", question: "Quel terme désigne les hadiths du Prophète ﷺ rapportant la parole d'Allah ?", options: ["Hadith Sahih", "Hadith Qudsi", "Hadith Hasan", "Hadith Marfu"], correctIndex: 1, explanation: "Les hadiths Qudsi sont des paroles divines transmises par le Prophète ﷺ hors du Coran.", difficulty: .difficile, category: "Hadith"),
    ]
}
