default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_API_ISSUER_ID"],
      key_filepath: File.expand_path("~/.appstoreconnect/private_keys/AuthKey_#{ENV['APP_STORE_API_KEY_ID']}.p8"),
      duration: 1200,
      in_house: false
    )

    increment_build_number(
      build_number: Time.now.strftime("%Y%m%d%H%M"),
      xcodeproj: "QuranLock.xcodeproj"
    )

    build_app(
      scheme: "QuranLock",
      export_method: "app-store",
      sdk: "iphoneos",
      export_options: {
        provisioningProfiles: {
          "com.rezaimia.QuranLock" => "QuranLock AppStore"
        },
        signingStyle: "manual",
        teamID: "J875R59LND"
      },
      clean: true,
      output_directory: "./build",
      output_name: "QuranLock.ipa",
      xcargs: "DEVELOPMENT_TEAM=J875R59LND CODE_SIGN_IDENTITY='Apple Distribution' CODE_SIGN_STYLE=Manual PROVISIONING_PROFILE_SPECIFIER='QuranLock AppStore'"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )

    UI.success "QuranLock uploaded to TestFlight!"
  end
end
