ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "180"
ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "6"

default_platform(:ios)

platform :ios do
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_API_ISSUER_ID"],
      key_filepath: File.expand_path("~/.appstoreconnect/private_keys/AuthKey_#{ENV['APP_STORE_API_KEY_ID']}.p8"),
      duration: 1200,
      in_house: false
    )

    increment_build_number(
      build_number: Time.now.strftime("%Y%m%d%H%M"),
      xcodeproj: "QuranLock.xcodeproj"
    )

    build_app(
      scheme: "QuranLock",
      export_method: "app-store",
      sdk: "iphoneos",
      clean: true,
      output_directory: "./build",
      output_name: "QuranLock.ipa",
      xcargs: "CODE_SIGNING_ALLOWED=NO",
      export_options: {
        method: "app-store",
        teamID: "J875R59LND",
        signingStyle: "manual",
        provisioningProfiles: {
          "com.rezaimia.QuranLock" => "QuranLock AppStore New"
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )
  end
end
